### Run test 1
POST http://localhost:1234/test/run
Content-Type: application/json

{
  "serviceName": "{{serviceName}}",
  "token": "{{token}}",
  "ratePerSecond": 100,
  "testCount": 20000,
  "processingTimeMillis": 1500
}

### Stop running test to save time and resources
# @timeout 120
POST http://localhost:1234/test/stop/{{serviceName}}

accountName=acc-22, parallelRequests=20000, rateLimitPerSec=1100, price=5, averageProcessingTime=PT1.6S, enabled=true