### Run test remotely
# @timeout 120
POST http://77.234.215.138:34321/run
Content-Type: application/json

{
  "serviceName": "{{serviceName}}",
  "token": "{{token}}",
  "branch": "case-12",
  "accounts": "acc-19",
  "ratePerSecond": 100,
  "testCount": 50000,
  "processingTimeMillis": 10000000
}

### Stop running test to save credits
# @timeout 120
POST http://77.234.215.138:31234/test/stop/{{serviceName}}