# @timeout 120
POST http://213.170.70.30:4321/run
Content-Type: application/json

{
  "serviceName": {{serviceName}},
  "token": {{token}},
  "branch": "main",
  "ratePerSecond": 2,
  "testCount": 10,
  "processingTimeMillis": 1000,
  "onPremises": true
}